package view;

import controller.ProdutoDao;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.ProdutoBean;

/**
 *
 * @author Guilherme / Julio / Francisco
 */
public class FrmCadastroProduto extends javax.swing.JInternalFrame
        implements IViewMetodosPadrao, IOuvintesPadrao, ITeclasPadrao {

    public List<ProdutoBean> produtos = new ArrayList<ProdutoBean>();
    public int intPosition = 0;
    public boolean booInclusao = false;
    public boolean booAlteracao = false;
    private boolean booAddTable = true;
    MaskFormatter mfPreco;
    public DefaultTableModel defaultTableModel = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    ;
    private static FrmCadastroProduto _instance = null;

    public static synchronized FrmCadastroProduto getInstance() {
        if (_instance == null) {
            _instance = new FrmCadastroProduto();
        }
        return _instance;
    }

    /**
     * Creates new form FrmCadastroProduto
     */
    private FrmCadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCadastroClientes = new javax.swing.JPanel();
        lblCodProd = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtPreco = new javax.swing.JFormattedTextField();
        txtDescricao = new javax.swing.JTextField();
        tobNavegador = new javax.swing.JToolBar();
        btnPrimeiro = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        txtContador = new javax.swing.JTextField();
        lblContador = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProdutos = new javax.swing.JTable();
        lblDescricao = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastrar Produtos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnlCadastroClientes.setBackground(new java.awt.Color(254, 254, 204));

        lblCodProd.setText("CÓDIGO:");

        lblPreco.setText("PREÇO: R$");

        txtCod.setEditable(false);
        txtCod.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCod.setText("1");
        txtCod.setOpaque(false);

        txtPreco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPreco.setEnabled(false);
        txtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecoKeyReleased(evt);
            }
        });

        txtDescricao.setEnabled(false);
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyReleased(evt);
            }
        });

        tobNavegador.setBackground(new java.awt.Color(254, 254, 150));
        tobNavegador.setRollover(true);

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/primeiro.png"))); // NOI18N
        btnPrimeiro.setFocusable(false);
        btnPrimeiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrimeiro.setOpaque(false);
        btnPrimeiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });
        btnPrimeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnPrimeiroKeyReleased(evt);
            }
        });
        tobNavegador.add(btnPrimeiro);

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/anterior.png"))); // NOI18N
        btnVoltar.setFocusable(false);
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVoltar.setOpaque(false);
        btnVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnVoltarKeyReleased(evt);
            }
        });
        tobNavegador.add(btnVoltar);
        tobNavegador.add(jSeparator1);

        txtContador.setText("0");
        txtContador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContadorKeyReleased(evt);
            }
        });
        tobNavegador.add(txtContador);

        lblContador.setText("de ( 0 )");
        tobNavegador.add(lblContador);
        tobNavegador.add(jSeparator2);

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/proximo.png"))); // NOI18N
        btnProximo.setFocusable(false);
        btnProximo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProximo.setOpaque(false);
        btnProximo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        btnProximo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnProximoKeyReleased(evt);
            }
        });
        tobNavegador.add(btnProximo);

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/ultimo.png"))); // NOI18N
        btnUltimo.setFocusable(false);
        btnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUltimo.setOpaque(false);
        btnUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        btnUltimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnUltimoKeyReleased(evt);
            }
        });
        tobNavegador.add(btnUltimo);
        tobNavegador.add(jSeparator3);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/add-2-icon (2)_1.png"))); // NOI18N
        btnAdicionar.setFocusable(false);
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setOpaque(false);
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnAdicionarKeyReleased(evt);
            }
        });
        tobNavegador.add(btnAdicionar);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/alterar.png"))); // NOI18N
        btnAlterar.setFocusable(false);
        btnAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlterar.setOpaque(false);
        btnAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnAlterarKeyReleased(evt);
            }
        });
        tobNavegador.add(btnAlterar);

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/delete-icon.png"))); // NOI18N
        btnDeletar.setFocusable(false);
        btnDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeletar.setOpaque(false);
        btnDeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeletar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnDeletarKeyReleased(evt);
            }
        });
        tobNavegador.add(btnDeletar);
        tobNavegador.add(jSeparator4);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/basic-data-icon.png"))); // NOI18N
        btnSalvar.setEnabled(false);
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setOpaque(false);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSalvarKeyReleased(evt);
            }
        });
        tobNavegador.add(btnSalvar);

        btnCancelar.setEnabled(false);
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setOpaque(false);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnCancelarKeyReleased(evt);
            }
        });
        tobNavegador.add(btnCancelar);

        tabProdutos.setBackground(new java.awt.Color(255, 255, 204));
        tabProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabProdutos.setGridColor(new java.awt.Color(255, 255, 0));
        tabProdutos.setSelectionBackground(new java.awt.Color(255, 255, 130));
        tabProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProdutosMouseClicked(evt);
            }
        });
        tabProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabProdutos);

        lblDescricao.setText("DESCRIÇÃO:");

        javax.swing.GroupLayout pnlCadastroClientesLayout = new javax.swing.GroupLayout(pnlCadastroClientes);
        pnlCadastroClientes.setLayout(pnlCadastroClientesLayout);
        pnlCadastroClientesLayout.setHorizontalGroup(
            pnlCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroClientesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCodProd)
                .addGap(4, 4, 4)
                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(lblPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tobNavegador, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
            .addGroup(pnlCadastroClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        pnlCadastroClientesLayout.setVerticalGroup(
            pnlCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroClientesLayout.createSequentialGroup()
                .addComponent(tobNavegador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCadastroClientesLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(lblCodProd))
                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPreco)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCadastroClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        setData(0);
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        setData(intPosition - 1);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        setData(intPosition + 1);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        setData(produtos.size() - 1);
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        _instance = null;
        setVisible(false);
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnPrimeiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPrimeiroKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnPrimeiroKeyReleased

    private void btnVoltarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnVoltarKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnVoltarKeyReleased

    private void txtContadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContadorKeyReleased
        performNavigateAction(evt);
        int intKeyCode = evt.getKeyCode();

        // Verifica se foi realmente digitado um número, caso não, o caractere 
        // digitado é apagado
        switch (intKeyCode) {
            case KeyEvent.VK_0:
                break;
            case KeyEvent.VK_1:
                break;
            case KeyEvent.VK_2:
                break;
            case KeyEvent.VK_3:
                break;
            case KeyEvent.VK_4:
                break;
            case KeyEvent.VK_5:
                break;
            case KeyEvent.VK_6:
                break;
            case KeyEvent.VK_7:
                break;
            case KeyEvent.VK_8:
                break;
            case KeyEvent.VK_9:
                break;
            case KeyEvent.VK_NUMPAD0:
                break;
            case KeyEvent.VK_NUMPAD1:
                break;
            case KeyEvent.VK_NUMPAD2:
                break;
            case KeyEvent.VK_NUMPAD3:
                break;
            case KeyEvent.VK_NUMPAD4:
                break;
            case KeyEvent.VK_NUMPAD5:
                break;
            case KeyEvent.VK_NUMPAD6:
                break;
            case KeyEvent.VK_NUMPAD7:
                break;
            case KeyEvent.VK_NUMPAD8:
                break;
            case KeyEvent.VK_NUMPAD9:
                break;
            default:
                txtContador.setText(txtContador.getText().replace(
                        evt.getKeyChar(), ' ').trim());
                break;
        }
        if (intKeyCode == KeyEvent.VK_ENTER) {
            setData(Integer.parseInt(txtContador.getText()) - 1);
        }
    }//GEN-LAST:event_txtContadorKeyReleased

    private void btnProximoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnProximoKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnProximoKeyReleased

    private void btnUltimoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUltimoKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnUltimoKeyReleased

    private void btnAdicionarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnAdicionarKeyReleased

    private void btnAlterarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAlterarKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnAlterarKeyReleased

    private void btnDeletarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeletarKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnDeletarKeyReleased

    private void btnSalvarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnSalvarKeyReleased

    private void btnCancelarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_btnCancelarKeyReleased

    private void txtPrecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_txtPrecoKeyReleased

    private void txtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyReleased
        performNavigateAction(evt);
    }//GEN-LAST:event_txtDescricaoKeyReleased

    private void tabProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabProdutosKeyReleased
        performNavigateAction(evt);
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            if (booAlteracao) {
                btnCancelar.doClick();
                booAlteracao = false;
            } else if (booInclusao) {
                booInclusao = false;
            }
            setData(tabProdutos.getSelectedRow());
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            if (booAlteracao) {
                btnCancelar.doClick();
                booAlteracao = false;
            } else if (booInclusao) {
                booInclusao = false;
            }
            setData(tabProdutos.getSelectedRow());
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (booAlteracao) {
                btnCancelar.doClick();
                booAlteracao = false;
            } else if (booInclusao) {
                booInclusao = false;
            }
            setData(tabProdutos.getSelectedRow());
            btnAlterar.doClick();
        }
    }//GEN-LAST:event_tabProdutosKeyReleased

    private void tabProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProdutosMouseClicked
        switch (evt.getClickCount()) {
            case 1:
                if (booAlteracao) {
                    btnCancelar.doClick();
                    booAlteracao = false;
                } else if (booInclusao) {
                    booInclusao = false;
                }
                setData(tabProdutos.getSelectedRow());
                break;
            case 2:
                if (booAlteracao) {
                    btnCancelar.doClick();
                } else if (booInclusao) {
                    booInclusao = false;
                }
                setData(tabProdutos.getSelectedRow());
                btnAlterar.doClick();
                break;
        }
    }//GEN-LAST:event_tabProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FrmCadastroProduto().setVisible(true);
            }
        });
    }

    /**
     * Método responsável por preparar o Formulário para a inclusão de um novo
     * produto
     */
    public void novoProduto() {
        txtCod.setText("");
        txtContador.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
    }

    /**
     * Carregar um ProdutoBean contendo as informações de um único produto
     * 
     * @param codUser Código do cliente a ser carregado
     * @return ProdutoBean Um ProdutoBean contendo as informações do produto
     */
    public ProdutoBean carregaBean() {
        ProdutoBean bean = new ProdutoBean(txtDescricao.getText(),
                Double.parseDouble(txtPreco.getText().substring(2).trim().replace(',', '.')));
        return bean;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JPanel pnlCadastroClientes;
    private javax.swing.JTable tabProdutos;
    private javax.swing.JToolBar tobNavegador;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtContador;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtPreco;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setData(int index) {
        intPosition = index;
        txtContador.setText(String.valueOf(intPosition + 1));
        txtCod.setText(String.valueOf(produtos.get(index).getCodigo()));
        txtDescricao.setText(produtos.get(index).getDescricao());
        String strPreco = String.valueOf(produtos.get(index).getPreco());
        int intPonto = strPreco.indexOf(".");
        String strTemp = strPreco.substring(intPonto + 1);
        if (strTemp.length() == 1) {
            strPreco += "0";
        }
        txtPreco.setText(strPreco);

        if (intPosition > 0 && intPosition < produtos.size() - 1) {
            btnPrimeiro.setEnabled(true);
            btnVoltar.setEnabled(true);
            btnProximo.setEnabled(true);
            btnUltimo.setEnabled(true);
        } else {
            if (intPosition == 0) {
                setEnabledNavigator(false);
            } else if (intPosition == produtos.size() - 1) {
                setEnabledNavigator(true);
            }
        }
    }

    @Override
    public void setEnabledNavigator(boolean b) {
        btnPrimeiro.setEnabled(b);
        btnVoltar.setEnabled(b);
        btnProximo.setEnabled(!b);
        btnUltimo.setEnabled(!b);
    }

    @Override
    public void setEnabledToolBar(boolean b) {
        btnAdicionar.setEnabled(b);
        btnAlterar.setEnabled(b);
        btnDeletar.setEnabled(b);
        txtContador.setEnabled(b);
        btnSalvar.setEnabled(!b);
        btnCancelar.setEnabled(!b);
    }

    @Override
    public void setActionListener(ActionListener al) {
        btnAdicionar.addActionListener(al);
        btnAdicionar.setActionCommand("Adicionar");
        btnDeletar.addActionListener(al);
        btnDeletar.setActionCommand("Deletar");
        btnAlterar.addActionListener(al);
        btnAlterar.setActionCommand("Alterar");
        btnSalvar.addActionListener(al);
        btnSalvar.setActionCommand("Salvar");
        btnCancelar.addActionListener(al);
        btnCancelar.setActionCommand("Cancelar");
    }

    @Override
    public void habilitaCampos(boolean b) {
        txtDescricao.setEnabled(b);
        txtPreco.setEnabled(b);
    }

    @Override
    public void limpaCampos() {
        txtCod.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
    }

    @Override
    public void atualizaTable() {
        if (booAddTable) {
            tabProdutos.setModel(defaultTableModel);
            booAddTable = false;
        }
    }

    public void addProduto(ProdutoBean produto) {
        produtos.add(produto);
        lblContador.setText("de ( " + produtos.size() + " )");
        Object o[] = {
            produtos.get(produtos.size() - 1).getCodigo(),
            produtos.get(produtos.size() - 1).getDescricao(),
            produtos.get(produtos.size() - 1).getPreco()
        };
        defaultTableModel.addRow(o);
    }

    @Override
    public void atualizaToolbar(boolean novo) {
        lblContador.setText("de ( " + produtos.size() + " )");
        if (novo && !produtos.isEmpty()) {
            setData(produtos.size() - 1);
        } else if (!produtos.isEmpty()) {
            setData(intPosition);
        }
    }

    @Override
    public void begin() {
        try {
            mfPreco = new MaskFormatter("##,##");
            mfPreco.setPlaceholderCharacter('_');
            mfPreco.setValueContainsLiteralCharacters(true);
            mfPreco.setValueClass(String.class);
            DefaultFormatterFactory dffPreco = new DefaultFormatterFactory(mfPreco);
            txtPreco.setFormatterFactory(dffPreco);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um ParseException"
                    + " na aplicação do MaskFormatter: " + e.getMessage(), "Erro:",
                    JOptionPane.ERROR_MESSAGE);
        }

        defaultTableModel.addColumn("Cod.");
        defaultTableModel.addColumn("Produto");
        defaultTableModel.addColumn("Preço");
        try {
            ProdutoDao dao = new ProdutoDao();
            produtos = dao.pesquisar();
            for (int i = 0; i < produtos.size(); i++) {
                Object[] o = {
                    produtos.get(i).getCodigo(),
                    produtos.get(i).getDescricao(),
                    produtos.get(i).getPreco()
                };
                defaultTableModel.addRow(o);
            }
            atualizaTable();
            atualizaToolbar(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FrmCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (!produtos.isEmpty()) {
            setData(0);
        }
    }

    @Override
    public void performAction(KeyEvent evt) {
    }

    @Override
    public void performNavigateAction(KeyEvent evt) {
        if (evt.isControlDown() && evt.isShiftDown()) {
            switch (evt.getKeyCode()) {
                case KeyEvent.VK_RIGHT:
                    btnUltimo.doClick();
                    break;
                case KeyEvent.VK_LEFT:
                    btnPrimeiro.doClick();
                    break;
            }
        } else if (evt.isControlDown()) {
            switch (evt.getKeyCode()) {
                case KeyEvent.VK_RIGHT:
                    btnProximo.doClick();
                    break;
                case KeyEvent.VK_LEFT:
                    btnVoltar.doClick();
                    break;
            }
        }
    }
}
