package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fp0520111064
 */
public class FrmMenu extends javax.swing.JFrame
        implements IOuvintesPadrao {
    
    private Timer timer = new Timer(1000, new ActionListener() {
        
        @Override
        public void actionPerformed(ActionEvent e) {
            Date date = new Date(System.currentTimeMillis());
            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
            lblDataHora.setText(sdf.format(date));
        }
    });
    private static FrmMenu _instance = null;
    
    public static synchronized FrmMenu getInstance() {
        if (_instance == null) {
            _instance = new FrmMenu();
        }
        _instance.setExtendedState(MAXIMIZED_BOTH);
        _instance.setIconImage(new ImageIcon("C:/PastellySystem/Imagens/pastelly.png").getImage());
        return _instance;
    }

    /**
     * Creates new form tela
     */
    private FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        pnlInicial = new javax.swing.JPanel();
        pnlBotoes = new javax.swing.JPanel();
        btnCadastrarCliente = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        btnNovaReserma = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        btnConsultarProduto = new javax.swing.JButton();
        btnConsultarReservas = new javax.swing.JButton();
        btnNovaVenda = new javax.swing.JButton();
        dpnInicial = new javax.swing.JDesktopPane();
        lblLogo = new javax.swing.JLabel();
        pnlBarInicial = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblDataHora = new javax.swing.JLabel();
        mnbInicial = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        miCadastrarClientes = new javax.swing.JMenuItem();
        miCadastrarProdutos = new javax.swing.JMenuItem();
        miCadastrarReservaMesa = new javax.swing.JMenuItem();
        miCadastrarVenda = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        miConsultarClientes = new javax.swing.JMenuItem();
        miConsultarProdutos = new javax.swing.JMenuItem();
        miConsultarReservas = new javax.swing.JMenuItem();
        miConsultarVenda = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        miRelatorioCliente = new javax.swing.JMenuItem();
        miRelatorioProduto = new javax.swing.JMenuItem();
        miRelatorioReserva = new javax.swing.JMenuItem();
        miRelatorioVenda = new javax.swing.JMenuItem();
        mnFerramentas = new javax.swing.JMenu();
        miUsuarioAtual = new javax.swing.JMenuItem();
        jsprFerramentas = new javax.swing.JPopupMenu.Separator();
        miBackup = new javax.swing.JMenuItem();
        mnAjuda = new javax.swing.JMenu();
        miManual = new javax.swing.JMenuItem();
        miAjudaOn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSobre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pastelaria Matryuska");
        setBackground(new java.awt.Color(255, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        pnlInicial.setBackground(new java.awt.Color(255, 255, 153));
        pnlInicial.setForeground(new java.awt.Color(255, 255, 102));
        pnlInicial.setToolTipText("Menu Inicial");

        pnlBotoes.setBackground(new java.awt.Color(255, 255, 204));

        btnCadastrarCliente.setFont(new java.awt.Font("Tahoma", 0, 18));
        btnCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Add-Male-User-icon.png"))); // NOI18N
        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotoes.add(btnCadastrarCliente);

        btnCadastrarProduto.setFont(new java.awt.Font("Tahoma", 0, 18));
        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Package-Add-icon.png"))); // NOI18N
        btnCadastrarProduto.setText("Cadastrar Produto");
        btnCadastrarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarProduto.setMaximumSize(new java.awt.Dimension(117, 23));
        btnCadastrarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotoes.add(btnCadastrarProduto);

        btnNovaReserma.setFont(new java.awt.Font("Tahoma", 0, 18));
        btnNovaReserma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/event-icon (1).png"))); // NOI18N
        btnNovaReserma.setText("Nova Reserva");
        btnNovaReserma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovaReserma.setMaximumSize(new java.awt.Dimension(117, 23));
        btnNovaReserma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotoes.add(btnNovaReserma);

        btnConsultarCliente.setFont(new java.awt.Font("Tahoma", 0, 18));
        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Search-Male-User-icon.png"))); // NOI18N
        btnConsultarCliente.setText("Consultar Cliente");
        btnConsultarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotoes.add(btnConsultarCliente);

        btnConsultarProduto.setFont(new java.awt.Font("Tahoma", 0, 18));
        btnConsultarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/product-icon-search.png"))); // NOI18N
        btnConsultarProduto.setText("Consultar Produto");
        btnConsultarProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotoes.add(btnConsultarProduto);

        btnConsultarReservas.setFont(new java.awt.Font("Tahoma", 0, 18));
        btnConsultarReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/event-search-icon.png"))); // NOI18N
        btnConsultarReservas.setText("Consultar Reservas");
        btnConsultarReservas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarReservas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotoes.add(btnConsultarReservas);

        btnNovaVenda.setFont(new java.awt.Font("Tahoma", 0, 18));
        btnNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/budget-icon.png"))); // NOI18N
        btnNovaVenda.setText("Nova Venda");
        btnNovaVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovaVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotoes.add(btnNovaVenda);

        dpnInicial.setBackground(new java.awt.Color(255, 255, 102));
        dpnInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLogo.setBackground(new java.awt.Color(255, 255, 153));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/LOGO_PASTELARIA_MATRYUSKA.png"))); // NOI18N
        lblLogo.setLabelFor(pnlInicial);
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogo.setFocusable(false);
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogo.setMaximumSize(new java.awt.Dimension(512, 384));
        lblLogo.setMinimumSize(new java.awt.Dimension(512, 384));
        lblLogo.setPreferredSize(new java.awt.Dimension(1024, 768));
        lblLogo.setBounds(0, 0, 1170, 500);
        dpnInicial.add(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlInicialLayout = new javax.swing.GroupLayout(pnlInicial);
        pnlInicial.setLayout(pnlInicialLayout);
        pnlInicialLayout.setHorizontalGroup(
            pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpnInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInicialLayout.setVerticalGroup(
            pnlInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInicialLayout.createSequentialGroup()
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dpnInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlBarInicial.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18));
        lblUsuario.setText("jLabel1");

        lblDataHora.setFont(new java.awt.Font("Tahoma", 0, 18));
        lblDataHora.setText("jLabel3");

        javax.swing.GroupLayout pnlBarInicialLayout = new javax.swing.GroupLayout(pnlBarInicial);
        pnlBarInicial.setLayout(pnlBarInicialLayout);
        pnlBarInicialLayout.setHorizontalGroup(
            pnlBarInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarInicialLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1035, Short.MAX_VALUE)
                .addComponent(lblDataHora)
                .addContainerGap())
        );
        pnlBarInicialLayout.setVerticalGroup(
            pnlBarInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUsuario)
                .addComponent(lblDataHora))
        );

        mnbInicial.setBackground(new java.awt.Color(255, 255, 227));
        mnbInicial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnCadastros.setText("Cadastros");

        miCadastrarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        miCadastrarClientes.setText("Clientes");
        mnCadastros.add(miCadastrarClientes);

        miCadastrarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miCadastrarProdutos.setText("Produtos");
        mnCadastros.add(miCadastrarProdutos);

        miCadastrarReservaMesa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miCadastrarReservaMesa.setText("Reserva de Mesa");
        mnCadastros.add(miCadastrarReservaMesa);

        miCadastrarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        miCadastrarVenda.setText("Vendas");
        mnCadastros.add(miCadastrarVenda);

        mnbInicial.add(mnCadastros);

        mnConsultas.setText("Consultas");

        miConsultarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        miConsultarClientes.setText("Cliente");
        mnConsultas.add(miConsultarClientes);

        miConsultarProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        miConsultarProdutos.setText("Produto");
        mnConsultas.add(miConsultarProdutos);

        miConsultarReservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miConsultarReservas.setText("Reserva");
        mnConsultas.add(miConsultarReservas);

        miConsultarVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        miConsultarVenda.setText("Venda");
        mnConsultas.add(miConsultarVenda);

        mnbInicial.add(mnConsultas);

        mnRelatorio.setText("Relatório");

        miRelatorioCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        miRelatorioCliente.setText("Relatório de Clientes");
        mnRelatorio.add(miRelatorioCliente);

        miRelatorioProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miRelatorioProduto.setText("Relatório de Produtos");
        mnRelatorio.add(miRelatorioProduto);

        miRelatorioReserva.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        miRelatorioReserva.setText("Relatório de Reservas");
        mnRelatorio.add(miRelatorioReserva);

        miRelatorioVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        miRelatorioVenda.setText("Relatório de Vendas");
        mnRelatorio.add(miRelatorioVenda);

        mnbInicial.add(mnRelatorio);

        mnFerramentas.setText("Ferramentas");

        miUsuarioAtual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        miUsuarioAtual.setText("Usuario Atual");
        mnFerramentas.add(miUsuarioAtual);
        mnFerramentas.add(jsprFerramentas);

        miBackup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        miBackup.setText("Backup");
        mnFerramentas.add(miBackup);

        mnbInicial.add(mnFerramentas);

        mnAjuda.setText("Ajuda");

        miManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miManual.setText("Manual");
        mnAjuda.add(miManual);

        miAjudaOn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        miAjudaOn.setText("Ajuda Online");
        mnAjuda.add(miAjudaOn);
        mnAjuda.add(jSeparator1);

        miSobre.setText("Sobre");
        mnAjuda.add(miSobre);

        mnbInicial.add(mnAjuda);

        setJMenuBar(mnbInicial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBarInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBarInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlInicial.getAccessibleContext().setAccessibleName("Menu Inicial");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        lblLogo.setSize(dpnInicial.getSize());
    }//GEN-LAST:event_formComponentResized
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Object[] options = {" Sim ", " Não "};
        if (JOptionPane.showOptionDialog(this, "Deseja realmente finalizar o "
                + "sistema?", "Aviso:", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1])
                == JOptionPane.YES_OPTION) {
            try {
                Calendar data = Calendar.getInstance();
                String backup = "" + data.get(Calendar.DAY_OF_MONTH) + "_"
                        + (data.get(Calendar.MONTH) + 1) + "_"
                        + data.get(Calendar.YEAR);
                String mysqldump = "C:/PastellySystem/Backups/mysqldump";
                File diretorio = new File("C:/PastellySystem/Backups");
                if (!diretorio.isDirectory()) {
                    new File("C:/PastellySystem/Backups").mkdir();
                }
                Process process = Runtime.getRuntime().exec("cmd /c "
                        + mysqldump + " -u root --password=root -c -e -K "
                        + "--single-transaction --databases matryuska > "
                        + "C:/PastellySystem/Backups/backup(" + backup + ").sql");
                process.waitFor();
                JOptionPane.showMessageDialog(this, "Backup criado em "
                        + diretorio + ", nao esqueca de salva-lo em sua "
                        + "midia externa.", "Backup Gerado",
                        JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
            } catch (InterruptedException ex) {
                Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowClosing
    
    public void statusbarInit(String usuario) {
        lblUsuario.setText("Usuario atual: " + usuario);
        timer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarProduto;
    private javax.swing.JButton btnConsultarReservas;
    private javax.swing.JButton btnNovaReserma;
    private javax.swing.JButton btnNovaVenda;
    public javax.swing.JDesktopPane dpnInicial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jsprFerramentas;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem miAjudaOn;
    private javax.swing.JMenuItem miBackup;
    private javax.swing.JMenuItem miCadastrarClientes;
    private javax.swing.JMenuItem miCadastrarProdutos;
    private javax.swing.JMenuItem miCadastrarReservaMesa;
    private javax.swing.JMenuItem miCadastrarVenda;
    private javax.swing.JMenuItem miConsultarClientes;
    private javax.swing.JMenuItem miConsultarProdutos;
    private javax.swing.JMenuItem miConsultarReservas;
    private javax.swing.JMenuItem miConsultarVenda;
    private javax.swing.JMenuItem miManual;
    private javax.swing.JMenuItem miRelatorioCliente;
    private javax.swing.JMenuItem miRelatorioProduto;
    private javax.swing.JMenuItem miRelatorioReserva;
    private javax.swing.JMenuItem miRelatorioVenda;
    private javax.swing.JMenuItem miSobre;
    private javax.swing.JMenuItem miUsuarioAtual;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnFerramentas;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JMenuBar mnbInicial;
    private javax.swing.JPanel pnlBarInicial;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlInicial;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setActionListener(ActionListener al) {
        miAjudaOn.addActionListener(al);
        miAjudaOn.setActionCommand("Exibir_Ajuda");
        miBackup.addActionListener(al);
        miBackup.setActionCommand("Exibir_Backup");
        miUsuarioAtual.addActionListener(al);
        miUsuarioAtual.setActionCommand("Exibir_Calculadora");
        miCadastrarClientes.addActionListener(al);
        miCadastrarClientes.setActionCommand("Exibir_CadastroCliente");
        miCadastrarProdutos.addActionListener(al);
        miCadastrarProdutos.setActionCommand("Exibir_CadastroProduto");
        miCadastrarReservaMesa.addActionListener(al);
        miCadastrarReservaMesa.setActionCommand("Exibir_NovaReserva");
        miCadastrarVenda.addActionListener(al);
        miCadastrarVenda.setActionCommand("Exibir_CadastroUsuario");
        miConsultarClientes.addActionListener(al);
        miConsultarClientes.setActionCommand("Exibir_ConsultaCliente");
        miConsultarProdutos.addActionListener(al);
        miConsultarProdutos.setActionCommand("Exibir_ConsultaProduto");
        miConsultarReservas.addActionListener(al);
        miConsultarReservas.setActionCommand("Exibir_ConsultaReserva");
        miManual.addActionListener(al);
        miManual.setActionCommand("Exibir_Manual");
        miSobre.addActionListener(al);
        miSobre.setActionCommand("Exibir_Sobre");
        miUsuarioAtual.addActionListener(al);
        miUsuarioAtual.setActionCommand("Exibir_UsuarioAtual");
        miRelatorioCliente.addActionListener(al);
        miRelatorioCliente.setActionCommand("Exibir_RelatorioCliente");
        miRelatorioProduto.addActionListener(al);
        miRelatorioProduto.setActionCommand("Exibir_RelatorioProduto");
        miRelatorioReserva.addActionListener(al);
        miRelatorioReserva.setActionCommand("Exibir_RelatorioReserva");
        miRelatorioVenda.addActionListener(al);
        miRelatorioVenda.setActionCommand("Exibir_RelatorioVenda");
        
        btnCadastrarCliente.addActionListener(al);
        btnCadastrarCliente.setActionCommand("Exibir_CadastroCliente");
        btnCadastrarProduto.addActionListener(al);
        btnCadastrarProduto.setActionCommand("Exibir_CadastroProduto");
        btnConsultarCliente.addActionListener(al);
        btnConsultarCliente.setActionCommand("Exibir_ConsultaCliente");
        btnConsultarProduto.addActionListener(al);
        btnConsultarProduto.setActionCommand("Exibir_ConsultaProduto");
        btnConsultarReservas.addActionListener(al);
        btnConsultarReservas.setActionCommand("Exibir_ConsultaReserva");
        btnNovaReserma.addActionListener(al);
        btnNovaReserma.setActionCommand("Exibir_NovaReserva");
        btnNovaVenda.addActionListener(al);
        btnNovaVenda.setActionCommand("Exibir_NovaVenda");
    }
}
